// Mock data used as fallback when MongoDB is unavailable
const mockUsers = [
  {
    id: '1',
    userId: 'admin01',
    name: 'Alex Morrison',
    email: 'alex.morrison@nexus.com',
    password: 'admin123', // plain for mock comparison
    role: 'Admin',
    department: 'Management',
    isActive: true,
    avatar: '',
    lastLogin: new Date(),
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    userId: 'user01',
    name: 'Priya Sharma',
    email: 'priya.sharma@nexus.com',
    password: 'user123',
    role: 'General User',
    department: 'Finance',
    isActive: true,
    avatar: '',
    lastLogin: new Date(),
    createdAt: new Date('2024-02-15'),
  },
  {
    id: '3',
    userId: 'user02',
    name: 'Jordan Lee',
    email: 'jordan.lee@nexus.com',
    password: 'user123',
    role: 'General User',
    department: 'HR',
    isActive: true,
    avatar: '',
    lastLogin: null,
    createdAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    userId: 'user03',
    name: 'Sam Chen',
    email: 'sam.chen@nexus.com',
    password: 'user123',
    role: 'General User',
    department: 'IT',
    isActive: false,
    avatar: '',
    lastLogin: null,
    createdAt: new Date('2024-03-20'),
  },
];

const mockRecords = [
  {
    id: 'r1', title: 'Q1 Budget Review', category: 'Finance',
    status: 'Completed', priority: 'High', accessLevel: 'all',
    assignedTo: 'user01', createdBy: 'admin01',
    description: 'Quarterly budget analysis and review for Finance department.',
    amount: 150000, dueDate: new Date('2024-03-31'),
    tags: ['budget', 'quarterly'], createdAt: new Date('2024-01-15'),
  },
  {
    id: 'r2', title: 'Server Infrastructure Upgrade', category: 'IT',
    status: 'In Progress', priority: 'Critical', accessLevel: 'all',
    assignedTo: 'user03', createdBy: 'admin01',
    description: 'Upgrade primary data center servers to latest hardware.',
    amount: 75000, dueDate: new Date('2024-06-30'),
    tags: ['infrastructure', 'upgrade'], createdAt: new Date('2024-02-01'),
  },
  {
    id: 'r3', title: 'Employee Onboarding Program', category: 'HR',
    status: 'In Progress', priority: 'Medium', accessLevel: 'all',
    assignedTo: 'user02', createdBy: 'user02',
    description: 'New structured onboarding program for 2024 hires.',
    amount: 12000, dueDate: new Date('2024-04-15'),
    tags: ['hr', 'onboarding'], createdAt: new Date('2024-02-20'),
  },
  {
    id: 'r4', title: 'Annual Salary Revision Report', category: 'HR',
    status: 'Pending', priority: 'High', accessLevel: 'admin',
    assignedTo: 'admin01', createdBy: 'admin01',
    description: 'Confidential salary revision details for all departments.',
    amount: 2400000, dueDate: new Date('2024-05-01'),
    tags: ['salary', 'confidential'], createdAt: new Date('2024-03-01'),
  },
  {
    id: 'r5', title: 'Marketing Campaign - Product Launch', category: 'Marketing',
    status: 'Pending', priority: 'High', accessLevel: 'all',
    assignedTo: 'user01', createdBy: 'user01',
    description: 'Launch campaign for new product line targeting enterprise clients.',
    amount: 50000, dueDate: new Date('2024-07-01'),
    tags: ['marketing', 'launch'], createdAt: new Date('2024-03-05'),
  },
  {
    id: 'r6', title: 'Revenue Forecast Q2-Q4', category: 'Finance',
    status: 'In Progress', priority: 'Critical', accessLevel: 'admin',
    assignedTo: 'admin01', createdBy: 'admin01',
    description: 'Executive-level confidential revenue projections.',
    amount: 5000000, dueDate: new Date('2024-04-30'),
    tags: ['revenue', 'forecast', 'confidential'], createdAt: new Date('2024-03-10'),
  },
  {
    id: 'r7', title: 'Cloud Migration Phase 1', category: 'IT',
    status: 'Pending', priority: 'High', accessLevel: 'all',
    assignedTo: 'user03', createdBy: 'admin01',
    description: 'Migrate legacy applications to AWS cloud infrastructure.',
    amount: 200000, dueDate: new Date('2024-08-31'),
    tags: ['cloud', 'migration', 'aws'], createdAt: new Date('2024-03-15'),
  },
  {
    id: 'r8', title: 'Sales Pipeline - Enterprise', category: 'Sales',
    status: 'In Progress', priority: 'Medium', accessLevel: 'all',
    assignedTo: 'user01', createdBy: 'user01',
    description: 'Track enterprise sales opportunities for Q2.',
    amount: 800000, dueDate: new Date('2024-06-30'),
    tags: ['sales', 'enterprise'], createdAt: new Date('2024-03-20'),
  },
  {
    id: 'r9', title: 'Vendor Contract Negotiations', category: 'Operations',
    status: 'Pending', priority: 'Medium', accessLevel: 'admin',
    assignedTo: 'admin01', createdBy: 'admin01',
    description: 'Confidential vendor contract terms and pricing negotiations.',
    amount: 300000, dueDate: new Date('2024-05-15'),
    tags: ['vendor', 'contract'], createdAt: new Date('2024-03-22'),
  },
  {
    id: 'r10', title: 'Team Training & Development', category: 'HR',
    status: 'Completed', priority: 'Low', accessLevel: 'all',
    assignedTo: 'user02', createdBy: 'user02',
    description: 'Annual training sessions for all departments.',
    amount: 25000, dueDate: new Date('2024-03-31'),
    tags: ['training', 'development'], createdAt: new Date('2024-01-20'),
  },
];

const getMockUsers = () => mockUsers;
const getMockRecords = () => mockRecords;
const mockComparePassword = (candidate, stored) => candidate === stored;

module.exports = { getMockUsers, getMockRecords, mockComparePassword };
